apiVersion: v2
name: vault-postgres
description: A Helm chart for HashiCorp Vault with PostgreSQL
type: application
version: 0.1.0
appVersion: "1.15.0"
dependencies:
  - name: postgresql
    version: "12.1.6"
    repository: "https://charts.bitnami.com/bitnami"
