apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
spec:
  replicas: {{ .Values.vault.replicaCount }}
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      serviceAccountName: {{ .Values.vault.serviceAccount.name }}
      containers:
        - name: vault
          image: {{ .Values.vault.image }}
          ports:
            - containerPort: 8200
          volumeMounts:
            - name: config
              mountPath: /vault/config
      volumes:
        - name: config
          configMap:
            name: vault-config
