apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: vault-postgres
data:
  vault.hcl: |
    storage "postgresql" {
      connection_url = "postgres://vault:vaultpassword@postgres-service:5432/vault?sslmode=disable"
    }
    listener "tcp" {
      address = "0.0.0.0:8200"
      tls_disable = 1
    }
